//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:28:45 AM EET 
//


package ua.nure.ageev.practice7.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gun complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gun">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Handy" type="{http://nure.ua/Firearms/p7}handy"/>
 *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="performance_characteristics" type="{http://nure.ua/Firearms/p7}Performance_characteristics"/>
 *         &lt;element name="Material" type="{http://nure.ua/Firearms/p7}material"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gun", propOrder = {

})
public class Gun {

    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "Handy", required = true)
    @XmlSchemaType(name = "string")
    protected Handy handy;
    @XmlElement(name = "Origin", required = true)
    protected String origin;
    @XmlElement(name = "performance_characteristics", required = true)
    protected PerformanceCharacteristics performanceCharacteristics;
    @XmlElement(name = "Material", required = true)
    @XmlSchemaType(name = "string")
    protected Material material;

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the handy property.
     * 
     * @return
     *     possible object is
     *     {@link Handy }
     *     
     */
    public Handy getHandy() {
        return handy;
    }

    /**
     * Sets the value of the handy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Handy }
     *     
     */
    public void setHandy(Handy value) {
        this.handy = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the performanceCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link PerformanceCharacteristics }
     *     
     */
    public PerformanceCharacteristics getPerformanceCharacteristics() {
        return performanceCharacteristics;
    }

    /**
     * Sets the value of the performanceCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformanceCharacteristics }
     *     
     */
    public void setPerformanceCharacteristics(PerformanceCharacteristics value) {
        this.performanceCharacteristics = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link Material }
     *     
     */
    public Material getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link Material }
     *     
     */
    public void setMaterial(Material value) {
        this.material = value;
    }

    @Override
    public String toString() {
        return "Gun{" +
                "model='" + model + '\'' +
                ", handy=" + handy +
                ", origin='" + origin + '\'' +
                ", performanceCharacteristics=" + performanceCharacteristics +
                ", material=" + material +
                '}';
    }
}
