//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:28:45 AM EET 
//


package ua.nure.ageev.practice7.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for handy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="handy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="one-handed"/>
 *     &lt;enumeration value="two-handed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "handy")
@XmlEnum
public enum Handy {

    @XmlEnumValue("one-handed")
    ONE_HANDED("one-handed"),
    @XmlEnumValue("two-handed")
    TWO_HANDED("two-handed");
    private final String value;

    Handy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Handy fromValue(String v) {
        for (Handy c: Handy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
