//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:28:45 AM EET 
//


package ua.nure.ageev.practice7.entity;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the src.ua.nure.ageev.practice7.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RangeLongRange_QNAME = new QName("", "long_range");
    private final static QName _RangeMiddleRange_QNAME = new QName("", "middle_range");
    private final static QName _RangeShortRange_QNAME = new QName("", "short_range");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: src.ua.nure.ageev.practice7.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Firearms }
     * 
     */
    public Firearms createFirearms() {
        return new Firearms();
    }

    /**
     * Create an instance of {@link Gun }
     * 
     */
    public Gun createGun() {
        return new Gun();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link PerformanceCharacteristics }
     * 
     */
    public PerformanceCharacteristics createPerformanceCharacteristics() {
        return new PerformanceCharacteristics();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "long_range", scope = Range.class)
    public JAXBElement<BigInteger> createRangeLongRange(BigInteger value) {
        return new JAXBElement<BigInteger>(_RangeLongRange_QNAME, BigInteger.class, Range.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "middle_range", scope = Range.class)
    public JAXBElement<Integer> createRangeMiddleRange(Integer value) {
        return new JAXBElement<Integer>(_RangeMiddleRange_QNAME, Integer.class, Range.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "short_range", scope = Range.class)
    public JAXBElement<Integer> createRangeShortRange(Integer value) {
        return new JAXBElement<Integer>(_RangeShortRange_QNAME, Integer.class, Range.class, value);
    }

}
