//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:28:45 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nure.ua/Firearms/p7")
package ua.nure.ageev.practice7.entity;
